# Generated by Django 2.1.4 on 2018-12-16 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProductID', models.IntegerField()),
                ('Manufacturer', models.CharField(max_length=200)),
                ('Name', models.CharField(max_length=200)),
                ('Price', models.CharField(max_length=200)),
                ('Car_type', models.CharField(max_length=200)),
                ('season', models.CharField(max_length=200)),
                ('approval', models.CharField(max_length=200)),
                ('speed_index', models.CharField(max_length=200)),
                ('weight_index', models.CharField(max_length=200)),
                ('sound_index', models.CharField(max_length=200)),
                ('production_year', models.CharField(max_length=200)),
                ('guaranty', models.CharField(max_length=200)),
                ('other_info', models.TextField()),
            ],
        ),
    ]
