# Generated by Django 2.1.4 on 2018-12-16 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etlapp', '0002_auto_20181216_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='country_of_origin',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='size',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='tire_width',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
