# Generated by Django 2.1.4 on 2018-12-29 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etlapp', '0003_auto_20181216_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='ProductID',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
